"""Minimal ULID generator: 48-bit millisecond timestamp + 80 random bits,
Crockford base32, 26 characters, lexically sortable by time. Message and
blob ids are ULIDs generated by the sender."""
import os
import time

_ALPHABET = "0123456789ABCDEFGHJKMNPQRSTVWXYZ"


def new_ulid() -> str:
    ts = int(time.time() * 1000)
    value = (ts << 80) | int.from_bytes(os.urandom(10), "big")
    out = []
    for _ in range(26):
        out.append(_ALPHABET[value & 31])
        value >>= 5
    return "".join(reversed(out))


def is_ulid(s: str) -> bool:
    return isinstance(s, str) and len(s) == 26 and all(c in _ALPHABET for c in s)
